In [1]:
import numpy as np

In [2]:
# 1. 生成一個等差數列，首數為0，尾數為20，公差為1的數列。
q1 = np.arange(0,21)
print(q1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# 2. 呈上題，將以上數列取出偶數。
q2 = []
for i in range(0, len(q1)):
    if(q1[i] % 2 == 0) :
        q2.append(q1[i])
        i = i +1
print(q2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [4]:
# 3. 呈1題，將數列取出3的倍數。
q3 = []
for i in range(1, len(q1)):
    if(q1[i] % 3 == 0) :
        q3.append(q1[i])
        i = i +1
print(q3)

[3, 6, 9, 12, 15, 18]


In [5]:
''' 
4. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

ans : 
 用 list()的方法只會將array第一層轉換成list
 而用 tolist() 會將所有層的陣列都轉成list
'''

' \n4. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？\n\nans : \n 用 list()的方法只會將array第一層轉換成list\n 而用 tolist() 會將所有層的陣列都轉成list\n'

In [6]:
# 5. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）
#import numpy as np

q5 = np.random.randint(20, size=10)
print(q5)
print(q5.ndim)
print(q5.shape)
print(q5.size)
print(q5.dtype)
print(q5.itemsize)
print(len(q5))

[18 13 11  6  2 12  0 17  1  6]
1
(10,)
10
int32
4
10


In [7]:
# 6. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
#import numpy as np
q6 = np.arange(12).reshape(3,4)
print(q6)

# list()
print(list(q6))

# tolist
print(q6.tolist())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
